# Generated by Django 2.2.6 on 2019-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='filmreview',
            old_name='year',
            new_name='premiere',
        ),
        migrations.AddField(
            model_name='filmreview',
            name='description',
            field=models.CharField(default='No description yet', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmreview',
            name='director',
            field=models.CharField(default='director', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmreview',
            name='category',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
