# Generated by Django 2.2.6 on 2019-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmreview',
            name='slug',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
    ]
