# Generated by Django 2.2.6 on 2019-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191012_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AlterField(
            model_name='filmreview',
            name='description',
            field=models.CharField(max_length=455),
        ),
        migrations.AddField(
            model_name='filmreview',
            name='characters',
            field=models.ManyToManyField(to='catalog.Characters'),
        ),
    ]
